include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.config.dart
    - lib/**.g.dart
    - build/**

linter:
  rules:
    avoid_function_literals_in_foreach_calls: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sized_box_for_whitespace: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
    use_key_in_widget_constructors: true

    omit_local_variable_types: false
    unawaited_futures: false
    sort_constructors_first: false