name: liquid_container
description: Liquid button container with Hover effect. Easily add liquid effect to your application
version: 1.0.4
homepage: https://www.linkedin.com/in/dmitry-okladnoy-359112159/
repository: https://github.com/Okladnoj/liquid_container

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
