name: liquid_container
description: Liquid button container with Hover effect. Easily add liquid effect to your application
version: 1.1.0
homepage: https://okladnoj-bio.web.app/
repository: https://github.com/Okladnoj/liquid_container

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
